<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>_assets\icone.ico</ApplicationIcon>
    <Title>Winform Calculator</Title>
    <Company>VLS Studio</Company>
    <Authors>Victor L Silva</Authors>
    <Copyright>Direitos a VLS Studio</Copyright>
    <PackageIcon>icone.jpg</PackageIcon>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/victorluansilva/vls-winforms-calculator</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="_assets\icone.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Update="_assets\icone.jpg">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="release\" />
  </ItemGroup>

</Project>